backend:
  name: github
  branch: main
  repo: MANGO2412/docwms

logo_url: http://localhost:3000/img/logo2.svg

# These lines should *not* be indented
media_folder: "static/img/upload" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/upload" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "docs_en_client"
  label: "ğŸ“ Client (EN)"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/client"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal"
  label: "ğŸ“ Internal (EN)"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal_receipt"
  label: "ğŸ“ Internal (EN) / Receipt"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal/Receipt"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal_packing"
  label: "ğŸ“ Internal (EN) / Packing"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal/Packing"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal_picking"
  label: "ğŸ“ Internal (EN) / Picking"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal/Picking"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal_shipping"
  label: "ğŸ“ Internal (EN) / Shipping"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal/Shipping"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_en_internal_wm"
  label: "ğŸ“ Internal (EN) / WM"
  folder: "i18n/en/docusaurus-plugin-content-docs/current/internal/WM"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_client"
  label: "ğŸ“ Client (ES)"
  folder: "docs/client"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal"
  label: "ğŸ“ Internal (ES)"
  folder: "docs/internal"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal_receipt"
  label: "ğŸ“ Internal (ES) / Receipt"
  folder: "docs/internal/Receipt"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal_picking"
  label: "ğŸ“ Internal (ES) / Picking"
  folder: "docs/internal/Picking"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal_packing"
  label: "ğŸ“ Internal (ES) / Packing"
  folder: "docs/internal/Packing"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal_shipping"
  label: "ğŸ“ Internal (ES) / Shipping"
  folder: "docs/internal/Shipping"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }

- name: "docs_es_internal_wm"
  label: "ğŸ“ Internal (ES) / WM"
  folder: "docs/internal/WM"
  create: true
  format: "frontmatter"
  fields:
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown" }
     - label: "Tags"
       name: "tags"
       widget: "list"
       fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }